/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/mifos-x-open-banking/blob/dev/LICENSE
 */
package org.mifosx.openbanking.core.database

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import org.mifosx.openbanking.core.database.banking.dao.AccountDao
import org.mifosx.openbanking.core.database.banking.dao.PaymentHistoryDao
import org.mifosx.openbanking.core.database.banking.dao.TransactionDao
import org.mifosx.openbanking.core.database.banking.entity.AccountEntity
import org.mifosx.openbanking.core.database.banking.entity.PaymentHistoryEntity
import org.mifosx.openbanking.core.database.banking.entity.TransactionEntity
import org.mifosx.openbanking.core.database.infra.dao.BookkeeperDao
import org.mifosx.openbanking.core.database.infra.dao.DraftDao
import org.mifosx.openbanking.core.database.infra.dao.FetchedAtDao
import org.mifosx.openbanking.core.database.infra.entity.BookkeeperEntity
import org.mifosx.openbanking.core.database.infra.entity.DraftEntity
import org.mifosx.openbanking.core.database.infra.entity.FetchedAtEntity
import org.mifosx.openbanking.core.database.sample.dao.SampleDao
import org.mifosx.openbanking.core.database.sample.entity.SampleEntity
import org.mifosx.openbanking.core.database.vrp.dao.VrpConsentDao
import org.mifosx.openbanking.core.database.vrp.dao.VrpPaymentDao
import org.mifosx.openbanking.core.database.vrp.entity.VrpConsentEntity
import org.mifosx.openbanking.core.database.vrp.entity.VrpPaymentEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 *
 * Room generates that `actual` during each platform's KSP task, which the metadata compilations
 * (`commonMain`, and the intermediate `nativeMain`) never see — so they would report the expect as
 * unimplemented. The suppression below is Room's documented answer to that, and it is the only
 * correct one: hand-writing an `actual` instead makes Room's own processor resolve the
 * `@ConstructedBy` target to a non-`expect` declaration and fail with "The @ConstructedBy definition
 * must be an 'expect' declaration", which breaks every native KSP task.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [template.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [org.mifosx.openbanking.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * @see org.mifosx.openbanking.core.database.sample.dao.SampleDao
 * @see org.mifosx.openbanking.core.database.sample.entity.SampleEntity
 */
@Database(
    entities = [
        SampleEntity::class,
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        AccountEntity::class,
        TransactionEntity::class,
        PaymentHistoryEntity::class,
        VrpConsentEntity::class,
        VrpPaymentEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    abstract val sampleDao: SampleDao
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao
    abstract val accountDao: AccountDao
    abstract val transactionDao: TransactionDao
    abstract val paymentHistoryDao: PaymentHistoryDao
    abstract val vrpConsentDao: VrpConsentDao
    abstract val vrpPaymentDao: VrpPaymentDao

    companion object {
        const val VERSION = 9
        const val DATABASE_NAME = "mifos_database.db"
    }
}
