/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package org.mifos.core.database

import androidx.room3.AutoMigration
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import androidx.room3.TypeConverters
import org.mifos.core.database.crypto.converter.FintechTypeConverters
import org.mifos.core.database.crypto.dao.CoinDetailDao
import org.mifos.core.database.crypto.dao.CoinMarketDao
import org.mifos.core.database.crypto.entity.CoinDetailEntity
import org.mifos.core.database.crypto.entity.CoinMarketEntity
import org.mifos.core.database.currency.converter.ChargeTypeConverters
import org.mifos.core.database.currency.dao.ExchangeRatesDao
import org.mifos.core.database.currency.dao.RateHistoryDao
import org.mifos.core.database.currency.entity.ExchangeRatesEntity
import org.mifos.core.database.currency.entity.RateHistoryEntity
import org.mifos.core.database.infra.dao.BookkeeperDao
import org.mifos.core.database.infra.dao.DraftDao
import org.mifos.core.database.infra.dao.FetchedAtDao
import org.mifos.core.database.infra.entity.BookkeeperEntity
import org.mifos.core.database.infra.entity.DraftEntity
import org.mifos.core.database.infra.entity.FetchedAtEntity
import org.mifos.core.database.sample.dao.SampleDao
import org.mifos.core.database.sample.entity.SampleEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic. The `@Suppress` is needed because the `actual`
 * is generated code, not hand-written.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [template.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [org.mifos.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * @see org.mifos.core.database.sample.dao.SampleDao
 * @see org.mifos.core.database.sample.entity.SampleEntity
 */
@Database(
    entities = [
        SampleEntity::class,
        ExchangeRatesEntity::class,
        CoinMarketEntity::class,
        CoinDetailEntity::class,
        RateHistoryEntity::class,
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        // v3 → v4: adds `framework_fetched_at` for durable lastFetchedAt timestamps.
        AutoMigration(from = 3, to = 4),
        // v4 → v5: adds `framework_submit_drafts` for offline-first form submission outbox.
        AutoMigration(from = 4, to = 5),
    ],
)
@TypeConverters(ChargeTypeConverters::class, FintechTypeConverters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    abstract val sampleDao: SampleDao
    abstract val exchangeRatesDao: ExchangeRatesDao
    abstract val coinMarketDao: CoinMarketDao
    abstract val coinDetailDao: CoinDetailDao
    abstract val rateHistoryDao: RateHistoryDao
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao

    companion object {
        const val VERSION = 5
        const val DATABASE_NAME = "mifos_database.db"
    }
}
